# Library title
TITLE := hotdrink

# Directory which holds original sources
SRCDIR := lib

# Directory to hold macro-expanded files
OBJDIR := objects

# Directory with test files
TESTDIR := tests

# Macro definitions
MACRODEFS := support/macros.m4

# Special JS file with namespace definitions
NSDEFS := ns.js

# sources are listed in are the order in which they will be concatenated
SOURCES := \
        utility/helpers.js \
        utility/observer.js \
        utility/rx.js \
        utility/graph.js \
        utility/promise.js \
        utility/pool.js \
        utility/async.js \
	model/variable.js \
        model/constraint.js \
        model/model.js \
        model/command.js \
        model/builder.js \
        runtime/binding.js \
        runtime/solver.js \
        runtime/stream.js \
        runtime/system.js \
	binders/edit.js \
	binders/text.js \
        binders/checkbox.js \
        binders/command.js \
        binders/css.js \
        binders/disabled.js \
        api.js

# Support files are copied into the test directory
SUPPORT := \
        support/worker.js