# Library title
TITLE := hotdrink

# Directory which holds original sources
SRCDIR := lib

# Directory to hold macro-expanded files
OBJDIR := objects

# Macro definitions
MACRODEFS := macros.m4

NSDEFS := ns.js

# sources are listed in are the order in which they will be concatenated
SOURCES := \
        utility/helpers.js \
        utility/observer.js \
        model/runtime.js \
        model/constraint.js \
	model/variable.js \
        model/model.js \
        runtime/solver.js \
        runtime/evaluator.js \
        runtime/runtime.js \
	binders/edit.js \
	binders/text.js \
        api.js
